$DuoIntegrationCompleter = {
    param (
        $CommandName,
        $ParamName,
        $Type,
        $CommandAst,
        $fakeBoundParameters
    )

    $Types = @'
[
  { "type": "1password", "Description": "1Password" },
  { "type": "accountsapi", "Description": "Accounts API" },
  { "type": "adfs", "Description": "Microsoft ADFS" },
  { "type": "adminapi", "Description": "Admin API" },
  { "type": "aeries", "Description": "Aeries SIS" },
  {
    "type": "agadobe_documentcloud",
    "Description": "SAML - Adobe Document Cloud"
  },
  { "type": "agaha", "Description": "SAML - Aha!" },
  { "type": "agasana", "Description": "SAML - Asana" },
  { "type": "agaws", "Description": "SAML - Amazon Web Services" },
  { "type": "agatlassian-cloud", "Description": "SAML - Atlassian Cloud" },
  { "type": "agbamboohr", "Description": "SAML - BambooHR" },
  { "type": "agbarracuda-waf", "Description": "SAML - Barracuda WAF" },
  { "type": "agbluejeans", "Description": "SAML - BlueJeans" },
  { "type": "agbomgar", "Description": "SAML - Bomgar" },
  { "type": "agbonusly", "Description": "SAML - Bonusly" },
  { "type": "agbox", "Description": "SAML - Box" },
  { "type": "agbugsnag", "Description": "SAML - Bugsnag" },
  { "type": "agcanvas", "Description": "SAML - Canvas" },
  { "type": "agclarizen", "Description": "SAML - Clarizen" },
  { "type": "agcloudlock", "Description": "SAML - CloudLock" },
  { "type": "agconfluence", "Description": "SAML - Confluence" },
  { "type": "agcrashplan", "Description": "SAML - CrashPlan" },
  {
    "type": "agcyberark",
    "Description": "SAML - CyberArk Privileged Account Security"
  },
  { "type": "agdatadog", "Description": "SAML - Datadog" },
  { "type": "agdesk", "Description": "SAML - Desk" },
  { "type": "agdigicert", "Description": "SAML - DigiCert" },
  { "type": "agdng", "Description": "SAML - Duo Network Gateway" },
  { "type": "agdocusign", "Description": "SAML - DocuSign" },
  { "type": "agdropbox", "Description": "SAML - Dropbox" },
  { "type": "agduo-adminpanel", "Description": "SAML - Duo Admin Panel" },
  { "type": "agegnyte", "Description": "SAML - Egnyte" },
  { "type": "agevernote", "Description": "SAML - Evernote" },
  { "type": "agexpensify", "Description": "SAML - Expensify" },
  { "type": "agfacebook", "Description": "SAML - Workplace by Facebook" },
  { "type": "agfreshdesk", "Description": "SAML - Freshdesk" },
  { "type": "aggeneric", "Description": "SAML - Service Provider" },
  {
    "type": "aggithub-business",
    "Description": "SAML - GitHub.com for Business"
  },
  { "type": "aggithub-enterprise", "Description": "SAML - GitHub Enterprise" },
  { "type": "aggoogle", "Description": "SAML - Google Workspace" },
  { "type": "aggotomeeting", "Description": "SAML - GoToMeeting" },
  { "type": "aggreenhouse", "Description": "SAML - Greenhouse" },
  { "type": "aghackerone", "Description": "SAML - HackerOne" },
  { "type": "aghackerrank", "Description": "SAML - HackerRank for Work" },
  { "type": "agheroku", "Description": "SAML - Heroku" },
  { "type": "aghipchat", "Description": "SAML - HipChat" },
  { "type": "agigloo", "Description": "SAML - Igloo" },
  { "type": "agintacct", "Description": "SAML - Intacct" },
  { "type": "agjamf-jss", "Description": "SAML - Jamf Pro" },
  { "type": "agjira", "Description": "SAML - JIRA" },
  { "type": "agjitbit", "Description": "SAML - Jitbit" },
  { "type": "aglooker", "Description": "SAML - Looker" },
  { "type": "agmarketo", "Description": "SAML - Marketo" },
  { "type": "agmeraki", "Description": "SAML - Meraki" },
  { "type": "agmonday", "Description": "SAML - Monday" },
  { "type": "agnamely", "Description": "SAML - Namely" },
  { "type": "agnetdocuments", "Description": "SAML - NetDocuments" },
  { "type": "agnewrelic", "Description": "SAML - New Relic" },
  { "type": "agoffice365", "Description": "SAML - Office 365" },
  { "type": "agopendns", "Description": "SAML - OpenDNS" },
  { "type": "agpagerduty", "Description": "SAML - PagerDuty" },
  {
    "type": "agpaloalto-aperture",
    "Description": "SAML - Palo Alto Networks Aperture"
  },
  { "type": "agpaloalto", "Description": "SAML - Palo Alto Networks" },
  { "type": "agremedyforce", "Description": "SAML - Remedyforce" },
  { "type": "agringcentral", "Description": "SAML - RingCentral" },
  { "type": "agrobin", "Description": "SAML - Robin" },
  { "type": "agsalesforce", "Description": "SAML - Salesforce" },
  { "type": "agsamanage", "Description": "SAML - Samanage" },
  { "type": "agsaucelabs", "Description": "SAML - Saucelabs" },
  { "type": "agsharefile", "Description": "SAML - ShareFile" },
  { "type": "agsignalsciences", "Description": "SAML - Signal Sciences" },
  { "type": "agslack", "Description": "SAML - Slack" },
  { "type": "agsmartsheet", "Description": "SAML - Smartsheet" },
  { "type": "agstatuspageio", "Description": "SAML - StatusPage.io" },
  { "type": "agsugarcrm", "Description": "SAML - SugarCRM" },
  { "type": "agsumologic", "Description": "SAML - Sumo Logic" },
  { "type": "agsyncplicity", "Description": "SAML - Syncplicity" },
  { "type": "agtableau-online", "Description": "SAML - Tableau Online" },
  { "type": "agtableau", "Description": "SAML - Tableau" },
  { "type": "agudemy", "Description": "SAML - Udemy" },
  { "type": "aguservoice", "Description": "SAML - UserVoice" },
  {
    "type": "agwebex",
    "Description": "SAML - Cisco Webex Meetings (with Site Admin)"
  },
  {
    "type": "agwebex-controlhub",
    "Description": "SAML - Cisco Webex (with Control Hub)"
  },
  { "type": "agworkday", "Description": "SAML - Workday" },
  { "type": "agzendesk", "Description": "SAML - Zendesk" },
  { "type": "agzoom", "Description": "SAML - Zoom" },
  {
    "type": "akamai-eaa",
    "Description": "Akamai Enterprise Application Access"
  },
  { "type": "array", "Description": "Array SSL VPN" },
  { "type": "aws-directory-service", "Description": "AWS Directory Service" },
  { "type": "azure-ca", "Description": "Microsoft Azure Active Directory" },
  { "type": "authapi", "Description": "Auth API" },
  { "type": "barracuda", "Description": "Barracuda SSL VPN" },
  { "type": "bitium", "Description": "Bitium" },
  { "type": "bitwarden", "Description": "Bitwarden" },
  { "type": "bomgar", "Description": "Bomgar" },
  { "type": "caradigm", "Description": "Caradigm" },
  { "type": "cas", "Description": "CAS (Central Authentication Service)" },
  { "type": "checkpoint", "Description": "Check Point VPN" },
  { "type": "cisco", "Description": "Cisco ASA SSL VPN" },
  {
    "type": "ciscofirepower",
    "Description": "Cisco Firepower Threat Defense VPN"
  },
  { "type": "ciscoiseradius", "Description": "Cisco ISE" },
  { "type": "ciscoradius", "Description": "Cisco RADIUS VPN" },
  { "type": "citrixcag", "Description": "Citrix Access Gateway" },
  {
    "type": "citrixns",
    "Description": "Citrix Gateway (formerly Citrix NetScaler)"
  },
  { "type": "clearpass", "Description": "Aruba ClearPass" },
  { "type": "confluence", "Description": "Confluence" },
  {
    "type": "cyberark",
    "Description": "CyberArk Privileged Account Security LDAP/RADIUS"
  },
  {
    "type": "cyberarkweb",
    "Description": "CyberArk Privileged Account Security"
  },
  { "type": "dag", "Description": "Duo Access Gateway Launcher" },
  {
    "type": "device-management-portal",
    "Description": "Device Management Portal"
  },
  { "type": "dng-ssh", "Description": "Duo Network Gateway - SSH Servers" },
  { "type": "dng", "Description": "Duo Network Gateway - Web Application" },
  { "type": "drawbridgenetworks", "Description": "OPAQ 360" },
  { "type": "drupal", "Description": "Drupal" },
  { "type": "epic", "Description": "Epic Hyperspace" },
  { "type": "f5bigip", "Description": "F5 BIG-IP APM" },
  { "type": "f5firepass", "Description": "F5 FirePass SSL VPN" },
  { "type": "fortinet", "Description": "Fortinet FortiGate SSL VPN" },
  { "type": "greyheller", "Description": "Appsian Security Platform" },
  { "type": "jira", "Description": "JIRA" },
  { "type": "juniper", "Description": "Juniper SSL VPN" },
  { "type": "juniperuac", "Description": "Juniper UAC" },
  { "type": "keeper", "Description": "Keeper Security" },
  { "type": "labtech", "Description": "LabTech Software" },
  { "type": "lastpass", "Description": "LastPass" },
  { "type": "ldapproxy", "Description": "LDAP Proxy" },
  { "type": "macos", "Description": "macOS" },
  { "type": "merakiradius", "Description": "Meraki RADIUS VPN" },
  { "type": "myworkdrive", "Description": "MyWorkDrive" },
  { "type": "netmotion", "Description": "NetMotion Mobility" },
  { "type": "oam", "Description": "Oracle Access Manager" },
  { "type": "okta", "Description": "Okta" },
  { "type": "onelogin", "Description": "OneLogin" },
  { "type": "openvpn", "Description": "OpenVPN" },
  { "type": "openvpnas", "Description": "OpenVPN Access Server" },
  { "type": "owa", "Description": "Microsoft OWA" },
  { "type": "paloalto", "Description": "Palo Alto SSL VPN" },
  { "type": "partner_authapi", "Description": "Partner Auth API" },
  { "type": "partner_websdk", "Description": "Partner WebSDK" },
  { "type": "pingfederate", "Description": "PingFederate" },
  {
    "type": "portal",
    "Description": "User Self-enrollment Portal (Bulk and Email enrollment)"
  },
  { "type": "radius", "Description": "RADIUS" },
  { "type": "rdgateway", "Description": "Microsoft RD Gateway" },
  { "type": "rdp", "Description": "Microsoft RDP" },
  { "type": "rdweb", "Description": "Microsoft RD Web" },
  { "type": "resilient", "Description": "Resilient Systems" },
  { "type": "rest", "Description": "Auth API" },
  { "type": "rras", "Description": "Microsoft RRAS" },
  { "type": "sailpoint", "Description": "SailPoint API" },
  { "type": "sailpointweb", "Description": "SailPoint Web" },
  { "type": "samlidp", "Description": "SAML IdP" },
  { "type": "shibboleth", "Description": "Shibboleth" },
  { "type": "sonicwallsra", "Description": "SonicWALL SRA SSL VPN" },
  { "type": "sophosutm", "Description": "Sophos UTM" },
  { "type": "splunk", "Description": "Splunk" },
  { "type": "thycotic", "Description": "Thycotic Secret Server" },
  { "type": "tmg", "Description": "Microsoft TMG" },
  { "type": "uag", "Description": "Microsoft UAG" },
  { "type": "unix", "Description": "Unix Application" },
  { "type": "verify", "Description": "Verify API" },
  { "type": "vmwareview", "Description": "VMWare View" },
  { "type": "websdk", "Description": "Web SDK" },
  { "type": "workday", "Description": "Workday" },
  { "type": "wordpress", "Description": "WordPress" }
]
'@ | ConvertFrom-Json
    $Types.type | Where-Object { $_ -like "$Type*" }
}

Register-ArgumentCompleter -CommandName New-DuoIntegration -ParameterName Type -ScriptBlock $DuoIntegrationCompleter
